### ISSUE TITLE
Have a way to search only aliases or only functions

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/shell-search#10]
Perhaps that would be useful.

**Comment by johnletey** [comment]
@nikitavoloboev Don't we already do this? They're two separate commands right now

**Comment by nikitavoloboev** [comment]
You are right. Closing this.

Do we also have a way to search through both aliases and functions?

**Comment by johnletey** [comment]
> Do we also have a way to search through both aliases and functions?

@nikitavoloboev No we do not ... you can open up an issue and I'll see what I can do about it in the morning
